USE [master]
GO

/****** Object:  Database [UserDAL]    Script Date: 05.10.2019 16:54:20 ******/
CREATE DATABASE [UserDAL]
 CONTAINMENT = NONE

ALTER DATABASE [UserDAL] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [UserDAL].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [UserDAL] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [UserDAL] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [UserDAL] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [UserDAL] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [UserDAL] SET ARITHABORT OFF 
GO

ALTER DATABASE [UserDAL] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [UserDAL] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [UserDAL] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [UserDAL] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [UserDAL] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [UserDAL] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [UserDAL] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [UserDAL] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [UserDAL] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [UserDAL] SET  DISABLE_BROKER 
GO

ALTER DATABASE [UserDAL] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [UserDAL] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [UserDAL] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [UserDAL] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [UserDAL] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [UserDAL] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [UserDAL] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [UserDAL] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [UserDAL] SET  MULTI_USER 
GO

ALTER DATABASE [UserDAL] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [UserDAL] SET DB_CHAINING OFF 
GO

ALTER DATABASE [UserDAL] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [UserDAL] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [UserDAL] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [UserDAL] SET  READ_WRITE 
GO

